### ISSUE TITLE
Can't pull in extra data

### ISSUE THREAD

**Issue by jamiesmith** [jamiesmith/kstars-on-osx#1]
when doing the startup wizard, get an error:

Loading of providers from file: https://edu.kde.org/kstars/downloads/providers.xml failed

**Comment by rlancaste** [comment]
Yes, that is correct.  unless you start it from the command line.  the download new data does not work when started from the app bundle yet.

**Comment by rlancaste** [comment]
there are some deployment steps we need to do to make that work
