### ISSUE TITLE
Few bugs with script

### ISSUE THREAD

**Issue by knro** [jamiesmith/kstars-on-osx#5]
Heya! Fantastic job on the script! I just executed it on my Mac mini and most stuff worked great. There was a problem in compiling one of KDE libraries in the craft, so it aborted. When I tried rerunning the script again, it complained that kstars-emerge already exists (should probably be renamed to kstars-craft).

I talked with Rob and he said I need to delete that, but why restart the whole process from scratch? Craft can continue from where ever it left off. If I change one line in KStars, I need to download and compile the whole KDE Stack again? 

Furthermore, the -f doesn't work, it says unknown option. Finally, is it possible to make the cmake version also builds the DMG? Thank you for your great work!

**Comment by rlancaste** [comment]
This was fixed awhile ago now, just never closed the issue.
